spring.datasource.url=jdbc:mysql://localhost:3306/poketradecenter?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
mybatis.mapper-locations=classpath*:com/poketradecenter/Mapper/implementaciones/*.xml
mybatis.type-aliases-package=com.poketradecenter.Clase